# Generated by Django 4.1.5 on 2023-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
